classes:
- name: dalmatian
  example_image: dalmatian.jpg
  concepts_groups:
  - true_label: dotted
    generated:
    - dotted_flux
    - dotted_gpti1
    - dotted_sd35
    bootstrap: true
    concept_ablation:
      example: dalmatian_undotted.jpg
      folder: dalmatian_undotted
  - true_label: fabric
    generated:
    - fabric_flux
    - fabric_gpti1
    - fabric_sd35
    bootstrap: true
    concept_ablation:
      example: dalmatian_unfabric.jpg
      folder: dalmatian_unfabric
  - true_label: spotted
    generated:
    - spotted_flux
    - spotted_gpti1
    - spotted_sd35
    bootstrap: true
    concept_ablation:
      example: dalmatian_unspotted.jpg
      folder: dalmatian_unspotted
models:
- name: ResNet50V2
  graph_path_filename: ResNet50V2-architecture-and-weights-compiled.h5
  label_path_filename: ResNet50V2-imagenet-classes.txt
  preprocessing_function: tensorflow.keras.applications.resnet_v2.preprocess_input
  max_examples: 500
  layers:
  - conv5_block1_out
  - conv5_block2_out
  - conv5_block3_out
- name: VGG16
  graph_path_filename: VGG16-architecture-and-weights-compiled.h5
  label_path_filename: VGG16-imagenet-classes.txt
  preprocessing_function: tensorflow.keras.applications.vgg16.preprocess_input
  max_examples: 500
  layers:
  - block5_conv1
  - block5_conv2
  - block5_conv3
- name: InceptionV3
  graph_path_filename: InceptionV3-architecture-and-weights-compiled.h5
  label_path_filename: InceptionV3-imagenet-classes.txt
  preprocessing_function: tensorflow.keras.applications.inception_v3.preprocess_input
  max_examples: 500
  layers:
  - mixed7
  - mixed8
  - mixed10
- name: ConvNeXt
  graph_path_filename: ConvNeXt-architecture-and-weights-compiled
  label_path_filename: ConvNeXt-imagenet-classes.txt
  preprocessing_function: tensorflow.keras.applications.convnext.preprocess_input
  max_examples: 500
  layers:
  - tf.__operators__.add_33
  - tf.__operators__.add_34
  - tf.__operators__.add_35
