[project]
name = "Visual-TCAV"
version = "0.1.0"
description = "A novel framework for post-hoc explainability in image classification"
authors = [{ name = "DataScience Polimi ", email = "datascience.polimi@gmail.com" }]
requires-python = ">=3.11,<3.13"
readme = "README.md"
dependencies = [
    "prettytable>=3.16.0,<4",
    "matplotlib>=3.10.1,<4",
    "tensorflow[and-cuda]==2.15.1",
    "tensorflow-probability==0.23.0",
    "tensorflow-metal>=1.2.0,<2 ; sys_platform == 'darwin'",
    "requests>=2.32.3,<3",
    "openai>=1.77.0,<2",
    "joblib>=1.5.0,<2",
    "pydantic>=2.11.4,<3",
    "pyyaml>=6.0.2,<7",
]

[dependency-groups]
dev = [
    "black>=23.9.1,<24",
    "isort>=5.12.0,<6",
]

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.hatch.build.targets.wheel]
include = ["src"]

