classes:
  - name: dalmatian
    example_image: dalmatian.jpg
    concepts_groups:
      - true_label: dotted
        generated:
          - dotted_flux_2
          - dotted_sd35_2
          - dotted_cgpt_2
        concept_imputation:
          example: undotted_dalmatian.png
          folder: undotted_dalmatian


models:
  - name: ResNet50V2
    graph_path_filename: ResNet50V2-architecture-and-weights-compiled.h5
    label_path_filename: ResNet50V2-imagenet-classes.txt
    preprocessing_function: tensorflow.keras.applications.resnet_v2.preprocess_input
    max_examples: 500
    layers:
      - "conv4_block3_out"
      - "conv4_block4_out"
      - "conv4_block5_out"
      - "conv4_block6_out"
      - "conv5_block1_out"
      - "conv5_block2_out"
      - "conv5_block3_out"